# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- task: ArtifactoryMaven@2
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'hts2'
    targetResolveReleaseRepo: 'ad-libs-release'
    targetResolveSnapshotRepo: 'ad-libs-snapshot'
    artifactoryDeployService: 'hts2'
    targetDeployReleaseRepo: 'ad-libs-release-local'
    targetDeploySnapshotRepo: 'ad-libs-snapshot-local'
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'hts2'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'DevOps'
